import Head from 'next/head'
import Board from './components/Board'

export default function Home() {

  return (
    <>
      <Head>
        <title>HTX July 4th Bingo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='site'>
        <div className='container'>
          <div>
            <h1>HTX July 4th Bingo 🤠 🧨 🇺🇸</h1>
            <Board />
          </div>
          <p>**Refresh page for new board</p>
        </div>
      </div>
    </>
  )
}
